
#Inventory sorter blacklists
[blacklists]
	#Container blacklist
	containerBlacklist = ["deeppouches:alpha_pouch", "deeppouches:beta_pouch", "cy.jdkdigital.productivebees.container.gui.AdvancedBeehiveScreen"]
	#Slot type blacklist
	slotBlacklist = []

