
#.
#Client-only settings - If you're looking for general settings, look inside your worlds serverconfig folder!
[client]
	#.
	#Higher density means more spawned particles.
	#Range: 0.0 ~ 1.0
	fanParticleDensity = 0.5

