
["Modifiers for tools"]
	#This configuration file is based on index. it means, 'legendary' -> '30' ->'generic.attack_damage;generic.attack_speed' -> '0.15;0.1' -> '2;2' is the first index, and in it, 'generic.attack_damage' -> '0.15' -> '2', 'generic.attack_speed' -> '0.1' -> '2'
	#You may need to make a resource pack to save the customization-required translation key for the attributes if the mod author didn't do that, or your customization on other mods' attribute may not look well
	#A hint on the translation key format: attribute.modxxx.attributexxx, e.g. attribute.minecraft.generic.attack_damage
	#The name of the modifier
	NAMES = []
	#The weight of the modifier in the modifiers pool
	WEIGHTS = []
	#The attribute of the modifier has. One modifier can have multiple attributes. Use ';' to split different attributes
	ATTRIBUTES = []
	#The amount used to calculate the attribute effect. Also can be multiple. Use ';' to split
	AMOUNTS = []
	#The operation ID of the attribute calculation. Can be three values: 0,1,2. 0 is ADDITION. 1 is MULTIPLY_BASE. 2 is MULTIPLY_TOTAL. you can refer to the calculation of the attributes already in the game
	OPERATIONS_IDS = []

